:green_heart: Update workflows
Signed-off-by: kei-g <km.8k6ce+github@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,21 +1,98 @@
-name: test
-on:
-  push:
-    branches: [ main ]
 jobs:
-  npm-test:
+  build:
+    continue-on-error: true
+    name: Build on Node.js ${{ matrix.node }}
+    outputs:
+      result: ${{ steps.build.outputs.result }}
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: false
       matrix:
-        node: [ '12.22.7', '14.17.6', '16.13.0', '17.1.0' ]
-    name: Test on Node.js ${{ matrix.node }}
+        node:
+          - '12.22.7'
+          - '14.17.6'
+          - '16.13.1'
+          - '17.2.0'
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 1
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
+          cache: 'npm'
           node-version: ${{ matrix.node }}
       - name: Setup modules
-        run: npm i
+        run: npm install
+      - name: Build
+        id: build
+        run: npm run build && echo "::set-output name=result::success"
+  coverage:
+    continue-on-error: true
+    name: Check code coverages on Node.js ${{ matrix.node }}
+    outputs:
+      result: ${{ steps.coverage.outputs.result }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        node:
+          - '12.22.7'
+          - '14.17.6'
+          - '16.13.1'
+          - '17.2.0'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 1
+      - name: Setup Node.js
+        uses: actions/setup-node@v2
+        with:
+          cache: 'npm'
+          node-version: ${{ matrix.node }}
+      - name: Setup modules
+        run: npm install
       - name: Test
-        run: npm test
+        id: coverage
+        run: npm test && echo "::set-output name=result::success"
+      - name: Archive code coverage report
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: code-coverage-report-${{ github.event.repository.name }}-${{ matrix.node }}
+          path: coverage
+  test:
+    name: Aggregate results
+    needs:
+      - build
+      - coverage
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check build result
+        run: test "${{ needs.build.outputs.result }}" = "success" || { echo "\x1b[31mFailed to build\x1b[m"; exit 1; }
+      - name: Check code coverages result
+        run: test "${{ needs.coverage.outputs.result }}" = "success" || { echo "\x1b[31mFailed to check code coverages\x1b[m"; exit 1; }
+name: test
+on:
+  pull_request:
+    branches:
+      - main
+    paths-ignore:
+      - '**.md'
+      - '.editorconfig'
+      - '.gitignore'
+      - '.npmignore'
+      - '.travis.yml'
+      - 'LICENSE'
+  push:
+    branches:
+      - main
+    paths-ignore:
+      - '**.md'
+      - '.editorconfig'
+      - '.gitignore'
+      - '.npmignore'
+      - '.travis.yml'
+      - 'LICENSE'
